[package]
name = "rust_perceptron"
version = "0.1.0"
authors = ["Tim Martin <tim@tim-martin.co.uk>"]
edition = "2018"

[dependencies]
rulinalg="0.4.2"
mnist="0.4.0"
rand="0.6.1"
mindtree_utils = "0.4.0"